---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lorem-go
  labels:
    app: lorem-go
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: lorem-go
    spec:
      containers:
      - name: lorem-go
        image: docker.io/sadokf/lorem-go:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
        resources:
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
---
apiVersion: v1
kind: Service
metadata:
  name: lorem-go
  labels:
    app: lorem-go
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: lorem-go
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lorem-go
spec:
  backend:
    serviceName: lorem-go
    servicePort: 3000
